### PR TITLE
Remove Swagger static configuration and add a template for the login page

### PR DESCRIPTION
**Pull request by emmanuel-h**

### CODE REVIEW

**Comment by emmanuel-h** [comment]
image

New Django login page

**Comment by thicham43** [comment]
I think we should not remove the _**admin_cohort/.env.example**_ file as it is meant to be a template for who ever wants to contribute to the project and create his own _**.env**_ file.
Also, we need to updated it to contain the same set of variables as .env and empty the values of some critical variables if necessary.

**Review by thicham43 — APPROVED** [review]

**Comment by Dubrzr** [comment]
Perso j'enlèverais le logo APHP Cohort360 étant un projet Open Source, mais bon on peut se reposer la question plus tard.
Sinon c bon pour moi

**Comment by emmanuel-h** [comment]
image

@Dubrzr we have the APHP logo on the Cohort login page as well.

But yes we can discuss about the usefulness of this logo.

**Comment by Dubrzr** [comment]
This should then be configurable maybe ^^

**Pull request merged**
